@ChecklistPoc.Api_HostAddress = http://localhost:5169

GET {{ChecklistPoc.Api_HostAddress}}/orders
Accept: application/json

###

POST {{ChecklistPoc.Api_HostAddress}}/orders
Content-Type: application/json
Accept: application/json

{
  "customerId": "CUST-123",
  "lines": [
    { "productCode": "P-1", "quantity": 2, "unitPrice": 10.5 }
  ]
}

###
